### ISSUE TITLE
TinyMCE height increases on every click, keypress, ...

### ISSUE THREAD

**Issue by nanobot248** [ProjectCleverWeb/Semantic-UI-WordPress#32] opened 2015-10-17 23:28 UTC
After installing this theme in Wordpress 4.3.1, i had a very annoying problem. Whenever i was editing posts or pages, the editor kept growing on every key-press, mouse click, mouse move and other events.
I don't know exactly what causes the problem, but the solution according to [1] is to add the following css statement:

`body#tinymce {height:auto !important;}`

I also posted this to the wordpress forum [2].

Regards,
Andreas

[1] - http://thisishow.info/wordpress-tinymce-editor-window-height-grows-when-clicking-inside-or-moving-cursor
[2] - https://wordpress.org/support/topic/texteditor-height-increases

**Comment by ProjectCleverWeb** [comment] 2015-10-19 14:05
Is this from the latest release or from the master branch?

**Comment by ProjectCleverWeb** [comment] 2015-10-19 14:21
Duplicate of issue #21

**Comment by ProjectCleverWeb** [comment] 2015-10-19 14:22
This problem appeared in the latest release but has since been fixed in master.

You can fix this by adding the following lines to your `main.css` file. (see commit 2a606f384758c1e9e93426d46fbf30a756709cc9 for details)

```css
html, body.mce-content-body {
	/* Fixes Post Editor */
	height: inherit !important;
}
```

---

**If you are seeing this in `develop`** please let me know what browser you are using and I reopen this issue and fix it.

**Closed by ProjectCleverWeb** 2015-10-19 14:22 UTC
Labels: duplicate
