### ISSUE TITLE
Extracting $GLOBALS causing OOM issues

### ISSUE THREAD

**Issue by johnjamesjacoby** [ProjectCleverWeb/Semantic-UI-WordPress#27] opened 2015-09-16 15:22 UTC
There are a few places where `$GLOBALS` is extracted into local scope. This duplicates the data stored in all global variables and causes huge memory spikes resulting in out-of-memory issues.

**Comment by ProjectCleverWeb** [comment] 2015-09-16 16:07
Duplicate of #29

**Closed by ProjectCleverWeb** 2015-09-16 16:07 UTC
Labels: duplicate
