### ISSUE TITLE
Duplicate core template functions

### ISSUE THREAD

**Issue by johnjamesjacoby** [ProjectCleverWeb/Semantic-UI-WordPress#28] opened 2015-09-16 15:27 UTC
It's almost impossible to learn how this theme works because it needlessly duplicates WordPress's core template location & loader functions.

The benefit of Semantic UI is it's convenience, and the prerequisite of needing to unwind this additional duplicated logic undoes that.

I'd like to see this go back to using WordPress's core functions, and let a theme author decide if something more sophisticated is necessary for their project.

**Comment by ProjectCleverWeb** [comment] 2015-09-16 16:08
duplicate of #29

**Closed by ProjectCleverWeb** 2015-09-16 16:08 UTC
Labels: duplicate
