### ISSUE TITLE
Media library is not functioning properly in 4.4.2

### ISSUE THREAD

**Issue by adamkpurdy** [ProjectCleverWeb/Semantic-UI-WordPress#39] opened 2016-03-25 19:56 UTC
Any time I try to upload media assets I get an error or try and use the media library when this theme is activated the media library pop over just hangs and doesn't load any images.

**Comment by krishaamer** [comment] 2016-04-04 22:51
Also having the same issue in 4.5. Upload works with other themes. Would it be possible to disable Semantic UI in the admin side?

**Comment by ProjectCleverWeb** [comment] 2016-04-05 13:50
Duplicate of #38

**Closed as completed by ProjectCleverWeb** 2016-04-05 13:50 UTC
Labels: bug, duplicate
